name: Build Windows GUI Executable

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller tkinter psutil pillow pywin32
    
    - name: Create assets directory
      run: |
        mkdir -p assets
        echo "# Placeholder for assets" > assets/README.md
    
    - name: Build Windows GUI executable
      run: |
        pyinstaller --onefile --windowed --name cleanshift --add-data "cleanshift;cleanshift" --add-data "assets;assets" --hidden-import tkinter --hidden-import PIL --hidden-import psutil --hidden-import win32api --hidden-import win32file cleanshift/main.py
    
    - name: Test executable exists
      run: |
        if (Test-Path "dist\cleanshift.exe") { 
          Write-Host "✅ Build successful" 
          $size = (Get-Item "dist\cleanshift.exe").Length / 1MB
          Write-Host "📦 Executable size: $([math]::Round($size, 2)) MB"
        } else { 
          Write-Host "❌ Build failed"
          exit 1 
        }
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cleanshift-windows-gui
        path: dist/cleanshift.exe
        retention-days: 30
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/cleanshift.exe
        body: |
          ## CleanShift GUI Release ${{ github.ref_name }}
          
          ### 🚀 Quick Install
          ```powershell
          iwr -useb https://github.com/theaathish/CleanShift/raw/main/install.ps1 | iex
          ```
          
          ### 📋 Manual Install
          1. Download `cleanshift.exe`
          2. Double-click to run
          3. No installation required!
          
          ### ✨ Features
          - Modern GUI interface
          - System cleanup and optimization
          - Drive space analysis
          - Application management
          - Development environment cleanup
          - Standalone executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
